#!/usr/bin/env python3
"""Generate src/pu_pipeline.py and src/pu_config.py from the built notebook.

The notebook is where the pipeline runtime is written and validated; this lifts
those cells into importable modules so the runner and the notebook cannot drift.
"""

import ast
import dataclasses
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
NB = ROOT / "notebooks" / "fathomnet_clef2026_pu_detection.ipynb"
SRC = ROOT / "src"

# Each marker must match exactly one cell, and no cell twice: an ambiguous
# marker silently duplicating a cell is the failure mode this guards against.
PIPELINE_MARKERS = [
    "def probe_environment():",
    "def ensure_images(",
    "def build_dataset_classes():",
    "def build_optimizer(model, cfg):",
    "def predict_two_scale(",
    "def harvest_over_dataset(",
    "def evaluate_map(",
    "def run_full_pipeline(",
]

PIPELINE_HEADER = '''"""Detector training, inference and pseudo-label harvesting.

Generated by build_pipeline_module.py -- edit the notebook, not this file.
"""

import collections
import hashlib
import json
import random
import time
from dataclasses import asdict
from pathlib import Path

import numpy as np

'''

CONFIG_HEADER = '''"""Pipeline configuration.

Generated by build_pipeline_module.py -- edit the notebook, not this file.
"""

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class PipelineConfig:'''


def code_cells():
    nb = json.loads(NB.read_text(encoding="utf-8"))
    return ["".join(c["source"]) for c in nb["cells"] if c["cell_type"] == "code"]


def definitions_only(src: str) -> str:
    """
    Keep a cell's imports, defs, classes and UPPER_CASE constants; drop the
    top-level statements that only make sense inside a notebook.

    Notebook cells mix definitions with the calls that exercise them --
    `ENV = probe_environment()`, `if CFG.stage in GPU_STAGES: ...`. Importing
    that as a module executes those calls against names that do not exist yet.
    """
    tree = ast.parse(src)
    lines = src.splitlines(keepends=True)
    kept = []

    for node in tree.body:
        keep = isinstance(
            node, (ast.Import, ast.ImportFrom, ast.FunctionDef,
                   ast.AsyncFunctionDef, ast.ClassDef)
        )
        # Module-level constants the functions rely on (URL_KEYS, ...), but not
        # computed ones like `ENV = probe_environment()`, which must not run on
        # import.
        if isinstance(node, ast.Assign):
            keep = all(
                isinstance(t, ast.Name) and t.id.isupper() for t in node.targets
            ) and isinstance(node.value, (ast.Constant, ast.Tuple, ast.List,
                                          ast.Dict, ast.Set))
        if not keep:
            continue
        start = node.lineno - 1
        # Include any decorators and the comment block directly above.
        if getattr(node, "decorator_list", None):
            start = min(start, node.decorator_list[0].lineno - 1)
        while start > 0 and lines[start - 1].lstrip().startswith("#"):
            start -= 1
        kept.append("".join(lines[start:node.end_lineno]).rstrip("\n"))

    return "\n\n\n".join(kept)


def build_pipeline(cells):
    picked, seen = [], set()
    for marker in PIPELINE_MARKERS:
        hits = [c for c in cells if marker in c]
        if not hits:
            raise SystemExit(f"marker not found in notebook: {marker!r}")
        src = hits[0]
        if src in seen:
            raise SystemExit(
                f"marker {marker!r} matched an already-extracted cell -- "
                "make it more specific"
            )
        seen.add(src)
        trimmed = definitions_only(src)
        picked.append(trimmed)
        print(f"  {marker:34s} {len(src):6d} -> {len(trimmed):6d} chars")

    out = SRC / "pu_pipeline.py"
    out.write_text(PIPELINE_HEADER + "\n\n\n".join(picked) + "\n", encoding="utf-8")
    ast.parse(out.read_text(encoding="utf-8"))
    print(f"  -> {out.name} ({out.stat().st_size} bytes)")


def build_config(cells):
    hits = [c for c in cells if "class CFG:" in c]
    if len(hits) != 1:
        raise SystemExit(f"expected exactly one CFG cell, found {len(hits)}")
    body = hits[0].split("class CFG:", 1)[1].split("CFG = CFG()", 1)[0].rstrip()

    out = SRC / "pu_config.py"
    out.write_text(CONFIG_HEADER + body + "\n", encoding="utf-8")
    ast.parse(out.read_text(encoding="utf-8"))

    sys.path.insert(0, str(SRC))
    for mod in ("pu_config",):
        sys.modules.pop(mod, None)
    from pu_config import PipelineConfig

    got = [f.name for f in dataclasses.fields(PipelineConfig)]
    want = re.findall(r"^\s{4}(\w+)\s*:", body, re.M)
    if got != want:
        raise SystemExit(f"config parity broken:\n  got  {got}\n  want {want}")
    print(f"  -> {out.name} ({len(got)} fields, parity verified)")


def main():
    if not NB.is_file():
        raise SystemExit(f"{NB} missing -- run build_notebook.py first")
    cells = code_cells()
    print("extracting pipeline runtime:")
    build_pipeline(cells)
    print("extracting config:")
    build_config(cells)
    print("done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
