"""Pipeline configuration.

Generated by build_pipeline_module.py -- edit the notebook, not this file.
"""

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class PipelineConfig:
    # ---- which stage to run -------------------------------------------------
    # "verify" | "audit" | "train_base" | "harvest" | "train_pu" | "infer"
    stage: str = "verify"

    # ---- paths --------------------------------------------------------------
    # Kaggle mounts competition data under /kaggle/input at an unpredictable
    # depth, so the annotation files are discovered rather than hardcoded.
    input_roots: tuple = ("/kaggle/input", "./data", ".")
    work_dir: str = "/kaggle/working" if Path("/kaggle/working").exists() else "./work"
    image_dir: str = ""        # set automatically; where frames are cached

    # ---- data ---------------------------------------------------------------
    num_classes: int = 32
    val_fraction: float = 0.15
    split_salt: str = "fathomnet-pu-v1"
    split_group_key: str = ""  # e.g. "source" if images carry a provenance field
    drop_tiny_boxes: bool = False

    # Cap the number of images actually used. Keep this small for a first
    # end-to-end pass; set to 0 for the full set.
    max_images: int = 200
    download_workers: int = 16

    # ---- model / training ---------------------------------------------------
    model_name: str = "PekingU/rtdetr_r50vd_coco_o365"
    img_size: int = 800          # Stage 2: the high-resolution training path
    batch_size: int = 2
    grad_accum: int = 4
    epochs: int = 2
    lr: float = 1e-4
    lr_backbone: float = 1e-5
    weight_decay: float = 1e-4
    clip_grad: float = 0.1
    num_workers: int = 2
    amp: bool = True
    seed: int = 1337

    # ---- Stage 3: pseudo-label recovery ------------------------------------
    pseudo_score_threshold: float = 0.60
    pseudo_gt_iou_threshold: float = 0.50
    pseudo_consistency_iou: float = 0.60
    pseudo_min_views: int = 2
    pseudo_max_per_image: int = 5

    # ---- Stage 4: PU-aware background loss ---------------------------------
    # The single most important setting in the notebook. pu_w_min must stay > 0:
    # at 0 the model gets no background supervision on its confident mistakes and
    # every rock and sediment texture becomes an organism.
    pu_w_min: float = 0.25
    pu_w_max: float = 1.00
    pu_tau: float = 0.50
    pu_temperature: float = 0.10
    pu_disabled: bool = False     # True = ordinary background loss (ablation)
    pseudo_label_weight: float = 0.50

    # ---- Stage 5: two-scale inference --------------------------------------
    infer_scales: tuple = (640, 960)
    infer_scale_weights: tuple = (1.0, 1.0)
    softnms_method: str = "gaussian"
    softnms_sigma: float = 0.50
    softnms_iou_threshold: float = 0.30
    score_threshold: float = 0.01
    max_dets_per_image: int = 100
