"""Detector training, inference and pseudo-label harvesting.

Generated by build_pipeline_module.py -- edit the notebook, not this file.
"""

import collections
import hashlib
import json
import random
import time
from dataclasses import asdict
from pathlib import Path

import numpy as np

def probe_environment():
    info = {}
    try:
        import torch
        info["torch"] = torch.__version__
        info["cuda"] = torch.cuda.is_available()
        info["n_gpu"] = torch.cuda.device_count() if torch.cuda.is_available() else 0
        if info["cuda"]:
            info["gpu_name"] = torch.cuda.get_device_name(0)
            info["gpu_mem_gb"] = round(
                torch.cuda.get_device_properties(0).total_memory / 1024**3, 1
            )
    except Exception as e:
        info["torch"] = f"MISSING ({e})"
        info["cuda"] = False
        info["n_gpu"] = 0

    for mod in ("torchvision", "transformers", "pycocotools", "scipy", "PIL"):
        try:
            m = __import__(mod)
            info[mod] = getattr(m, "__version__", "present")
        except Exception:
            info[mod] = "MISSING"

    info["on_kaggle"] = Path("/kaggle").exists()
    info["internet"] = False
    try:
        import urllib.request
        urllib.request.urlopen("https://huggingface.co", timeout=8)
        info["internet"] = True
    except Exception:
        pass
    return info


GPU_STAGES = {"all", "train_base", "harvest", "train_pu", "infer"}


import urllib.request


from concurrent.futures import ThreadPoolExecutor


URL_KEYS = ("coco_url", "url", "flickr_url", "image_url", "file_url")


def image_url(im: dict):
    for k in URL_KEYS:
        v = im.get(k)
        if isinstance(v, str) and v.startswith("http"):
            return v
    return None


def local_image_path(im: dict, cache_dir: Path) -> Path:
    """Stable on-disk name for an image record."""
    name = im.get("file_name") or ""
    if name and not name.startswith("http"):
        stem = Path(name).name
    else:
        url = image_url(im) or str(im["id"])
        stem = hashlib.sha1(url.encode()).hexdigest()[:20] + ".png"
    return cache_dir / stem


def find_attached_image_dir(roots, probe_names, max_probe=40):
    """Look for an already-attached directory containing the expected frames."""
    probe = {Path(n).name for n in probe_names if n}
    if not probe:
        return None
    for root in roots:
        root = Path(root)
        if not root.exists():
            continue
        for d in [root] + [p for p in root.rglob("*") if p.is_dir()][:2000]:
            try:
                names = {p.name for p in list(d.iterdir())[:2000] if p.is_file()}
            except Exception:
                continue
            if names and len(probe & names) >= min(3, len(probe)):
                return d
    return None


def image_cache_root(cfg):
    """
    Where downloaded frames live.

    Deliberately NOT work_dir: Kaggle caps a notebook's saved output at 20 GB and
    this dataset's imagery is roughly that on its own, so caching it in the output
    directory makes the commit fail at save time. /kaggle/temp is scratch -- large,
    and discarded with the session.
    """
    for scratch in ("/kaggle/temp", "/tmp"):
        if Path(scratch).is_dir():
            return Path(scratch) / "fathomnet_images"
    return Path(cfg.work_dir) / "images"


def ensure_images(coco, cache_dir, workers=16, verbose=True, deadline=None):
    """
    Make sure every image in `coco` exists on disk; download the missing ones.

    Returns (ok_image_ids, failed_image_ids). Images that cannot be fetched are
    reported rather than silently producing black frames.

    `deadline` (an absolute time.time()) caps how long downloading may take:
    FathomNet's throughput is not ours to control, and an unbounded fetch can eat
    a whole session before training starts. Whatever arrived by then is used.
    """
    cache_dir = Path(cache_dir)
    cache_dir.mkdir(parents=True, exist_ok=True)

    todo = []
    ok, failed = [], []
    for im in coco["images"]:
        p = local_image_path(im, cache_dir)
        im["_local_path"] = str(p)
        if p.is_file() and p.stat().st_size > 0:
            ok.append(im["id"])
        else:
            u = image_url(im)
            if u:
                todo.append((im["id"], u, p))
            else:
                failed.append(im["id"])

    if todo and verbose:
        print(f"downloading {len(todo)} frames with {workers} workers ...")

    def fetch(job):
        im_id, url, path = job
        for attempt in range(3):
            try:
                req = urllib.request.Request(
                    url, headers={"User-Agent": "fathomnet-pu-notebook/1.0"}
                )
                with urllib.request.urlopen(req, timeout=30) as r:
                    data = r.read()
                if not data:
                    raise IOError("empty response")
                tmp = path.with_suffix(path.suffix + ".part")
                tmp.write_bytes(data)
                tmp.rename(path)
                return im_id, True
            except Exception:
                time.sleep(1.5 * (attempt + 1))
        return im_id, False

    if todo:
        from concurrent.futures import as_completed

        t_start = time.time()
        seen_ids = set()
        with ThreadPoolExecutor(max_workers=workers) as ex:
            futures = [ex.submit(fetch, job) for job in todo]
            try:
                for n, fut in enumerate(as_completed(futures), 1):
                    im_id, good = fut.result()
                    seen_ids.add(im_id)
                    (ok if good else failed).append(im_id)
                    if verbose and n % 100 == 0:
                        rate = n / max(time.time() - t_start, 1e-6)
                        eta_min = (len(todo) - n) / max(rate, 1e-6) / 60.0
                        print(f"  {n}/{len(todo)}  {rate:.1f} img/s  "
                              f"eta {eta_min:.0f}m")
                    if deadline is not None and time.time() > deadline:
                        print(f"  >>> download budget spent after "
                              f"{n}/{len(todo)}; using what arrived")
                        break
            finally:
                for f in futures:
                    f.cancel()
        for im_id, _url, _path in todo:
            if im_id not in seen_ids:
                failed.append(im_id)

    if verbose:
        print(f"available: {len(ok)}   unavailable: {len(failed)}")
    return set(ok), set(failed)


def build_dataset_classes():
    """Defined inside a function so the CPU-only stages never import torch."""
    import torch
    from torch.utils.data import Dataset
    from PIL import Image

    IMAGENET_MEAN = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
    IMAGENET_STD = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)

    class FathomNetDataset(Dataset):
        """
        COCO-format marine detection dataset.

        Emits normalised cxcywh boxes and contiguous class indices in
        [0, num_classes). `is_pseudo` is carried through so the loss can trust
        human annotations more than harvested ones.
        """

        def __init__(self, coco, image_ids, cat_id_to_index, img_size,
                     train=True, hflip_p=0.5):
            self.img_size = int(img_size)
            self.train = train
            self.hflip_p = hflip_p
            self.cat_id_to_index = dict(cat_id_to_index)

            keep = set(image_ids)
            self.images = [im for im in coco["images"] if im["id"] in keep]
            self.by_image = collections.defaultdict(list)
            for a in coco["annotations"]:
                if a["image_id"] in keep:
                    self.by_image[a["image_id"]].append(a)

        def __len__(self):
            return len(self.images)

        def _load(self, im):
            path = im.get("_local_path")
            if path and Path(path).is_file():
                return Image.open(path).convert("RGB")
            raise FileNotFoundError(f"image {im['id']} not on disk")

        def __getitem__(self, i):
            im = self.images[i]
            try:
                pil = self._load(im)
            except Exception:
                # A missing frame must not kill an epoch, but it must be visible.
                pil = Image.new("RGB", (self.img_size, self.img_size), (0, 0, 0))
                W, H = pil.size
                return self._pack(pil, [], im["id"], W, H, missing=True)

            W, H = pil.size
            anns = self.by_image.get(im["id"], [])
            return self._pack(pil, anns, im["id"], W, H, missing=False)

        def _pack(self, pil, anns, image_id, W, H, missing):
            boxes, labels, is_pseudo = [], [], []
            for a in anns:
                x, y, w, h = a["bbox"]
                if w <= 0 or h <= 0:
                    continue
                idx = self.cat_id_to_index.get(a["category_id"])
                if idx is None:
                    continue
                # -> normalised cxcywh, invariant to the resize below.
                boxes.append([(x + w / 2) / W, (y + h / 2) / H, w / W, h / H])
                labels.append(idx)
                is_pseudo.append(bool(a.get("is_pseudo", False)))

            pil = pil.resize((self.img_size, self.img_size), Image.BILINEAR)

            if self.train and boxes and random.random() < self.hflip_p:
                pil = pil.transpose(Image.FLIP_LEFT_RIGHT)
                boxes = [[1.0 - b[0], b[1], b[2], b[3]] for b in boxes]

            x = torch.from_numpy(np.asarray(pil, dtype=np.float32).copy())
            x = x.permute(2, 0, 1) / 255.0
            x = (x - IMAGENET_MEAN) / IMAGENET_STD

            t = {
                "labels": torch.as_tensor(labels, dtype=torch.long),
                "boxes": torch.as_tensor(boxes, dtype=torch.float32).reshape(-1, 4),
                "is_pseudo": torch.as_tensor(is_pseudo, dtype=torch.bool),
                "image_id": int(image_id),
                "orig_size": (int(W), int(H)),
                "missing": bool(missing),
            }
            return x, t

    def collate(batch):
        xs = torch.stack([b[0] for b in batch])
        return xs, [b[1] for b in batch]

    return FathomNetDataset, collate


def build_category_maps(coco):
    """Contiguous 0..K-1 indices, with maps back to the competition's ids."""
    cats = sorted(coco["categories"], key=lambda c: c["id"])
    cat_id_to_index = {c["id"]: i for i, c in enumerate(cats)}
    index_to_cat_id = {i: c["id"] for i, c in enumerate(cats)}
    index_to_name = {i: c.get("name", str(c["id"])) for i, c in enumerate(cats)}
    return cat_id_to_index, index_to_cat_id, index_to_name


def build_model(num_classes, model_name, device):
    """
    RT-DETR with a fresh classification head sized to the challenge's classes.

    `ignore_mismatched_sizes=True` is what allows the pretrained COCO head to be
    replaced. Requires internet on first call; the weights then sit in the HF cache.
    """
    import torch
    from transformers import RTDetrForObjectDetection

    model = RTDetrForObjectDetection.from_pretrained(
        model_name, num_labels=num_classes, ignore_mismatched_sizes=True
    )
    model.to(device)
    return model


def build_optimizer(model, cfg):
    """
    AdamW with a lower LR on the pretrained backbone.

    Returns (optimizer, max_lrs) so the scheduler's max_lr always lines up with
    the param groups that actually exist -- an empty backbone group (if the
    parameter naming ever changes) would otherwise silently desynchronise them.
    """
    import torch

    backbone, rest = [], []
    for n, p in model.named_parameters():
        if not p.requires_grad:
            continue
        (backbone if "backbone" in n else rest).append(p)

    groups, max_lrs = [], []
    if rest:
        groups.append({"params": rest, "lr": cfg.lr})
        max_lrs.append(cfg.lr)
    if backbone:
        groups.append({"params": backbone, "lr": cfg.lr_backbone})
        max_lrs.append(cfg.lr_backbone)
    if not groups:
        raise RuntimeError("no trainable parameters found")

    print(f"param groups: head/neck {len(rest)} tensors, backbone {len(backbone)} tensors")
    return torch.optim.AdamW(groups, weight_decay=cfg.weight_decay), max_lrs


def make_grad_scaler(enabled):
    import torch
    try:
        return torch.amp.GradScaler("cuda", enabled=enabled)
    except (AttributeError, TypeError):
        return torch.cuda.amp.GradScaler(enabled=enabled)


def autocast_ctx(enabled):
    import torch
    try:
        return torch.amp.autocast("cuda", enabled=enabled)
    except (AttributeError, TypeError):
        return torch.cuda.amp.autocast(enabled=enabled)


def load_checkpoint(path, map_location):
    """torch.load flipped its weights_only default in 2.6; handle both."""
    import torch
    try:
        return torch.load(path, map_location=map_location, weights_only=False)
    except TypeError:
        return torch.load(path, map_location=map_location)


def train_one_run(coco, train_ids, val_ids, cfg, criterion_config,
                  ckpt_name, init_from=None, deadline=None):
    """
    Train the detector, checkpointing every epoch.

    Checkpointing every epoch is not optional on Kaggle: a session that hits the
    wall mid-run otherwise loses the entire GPU allocation it consumed.

    `deadline` is an absolute time.time() value. Training stops at the next step
    boundary once it passes, saves, and returns -- so a long run degrades into a
    shorter one instead of being killed with nothing on disk.
    """
    import torch
    from torch.utils.data import DataLoader

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    FathomNetDataset, collate = build_dataset_classes()
    cat_id_to_index, _, _ = build_category_maps(coco)

    ds_tr = FathomNetDataset(coco, train_ids, cat_id_to_index, cfg.img_size, train=True)
    ds_va = FathomNetDataset(coco, val_ids, cat_id_to_index, cfg.img_size, train=False)
    print(f"train images {len(ds_tr)} | val images {len(ds_va)}")

    dl_tr = DataLoader(ds_tr, batch_size=cfg.batch_size, shuffle=True,
                       num_workers=cfg.num_workers, collate_fn=collate,
                       drop_last=True, pin_memory=True)

    model = build_model(cfg.num_classes, cfg.model_name, device)
    if init_from and Path(init_from).is_file():
        model.load_state_dict(load_checkpoint(init_from, device)["model"])
        print(f"initialised from {init_from}")

    criterion = PUDetectionCriterion(criterion_config).to(device)
    optimizer, max_lrs = build_optimizer(model, cfg)
    steps_per_epoch = max(len(dl_tr) // cfg.grad_accum, 1)
    total_steps = max(steps_per_epoch * cfg.epochs, 1)
    scheduler = torch.optim.lr_scheduler.OneCycleLR(
        optimizer, max_lr=max_lrs, total_steps=total_steps, pct_start=0.1
    )
    use_amp = bool(cfg.amp and device.type == "cuda")
    scaler = make_grad_scaler(use_amp)

    ckpt_path = Path(cfg.work_dir) / ckpt_name
    history = []

    for epoch in range(cfg.epochs):
        model.train()
        running = collections.defaultdict(float)
        n_batches = 0
        t0 = time.time()
        optimizer.zero_grad(set_to_none=True)

        stopped_early = False
        for step, (pixel_values, targets) in enumerate(dl_tr):
            if deadline is not None and time.time() > deadline:
                print(f"  deadline reached at epoch {epoch} step {step}; "
                      "stopping cleanly")
                stopped_early = True
                break
            pixel_values = pixel_values.to(device, non_blocking=True)

            with autocast_ctx(use_amp):
                out = model(pixel_values=pixel_values)

            # The loss runs outside autocast: the Hungarian matching cost and the
            # focal/GIoU terms are numerically touchy in fp16, and this costs
            # nothing since the backbone forward is where the time goes.
            losses = criterion(
                {"logits": out.logits.float(), "pred_boxes": out.pred_boxes.float()},
                targets,
            )
            loss = losses["loss"] / cfg.grad_accum

            if not torch.isfinite(loss):
                print(f"  !! non-finite loss at step {step}, skipping batch")
                optimizer.zero_grad(set_to_none=True)
                continue

            scaler.scale(loss).backward()

            if (step + 1) % cfg.grad_accum == 0:
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), cfg.clip_grad)
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad(set_to_none=True)
                if scheduler.last_epoch < total_steps - 1:
                    scheduler.step()

            for k, v in losses.items():
                running[k] += float(v.detach().item() if hasattr(v, "item") else v)
            n_batches += 1

            if step % 50 == 0:
                print(
                    f"  e{epoch} s{step}/{len(dl_tr)} "
                    f"loss {losses['loss'].item():.3f} "
                    f"cls {losses['loss_class'].item():.3f} "
                    f"bbox {losses['loss_bbox'].item():.3f} "
                    f"matched {int(losses['num_matched'].item())} "
                    f"bg_w {losses['mean_bg_weight'].item():.3f} "
                    f"softened {int(losses['n_softened'].item())}"
                )

        epoch_stats = {k: v / max(n_batches, 1) for k, v in running.items()}
        epoch_stats["epoch"] = epoch
        epoch_stats["seconds"] = round(time.time() - t0, 1)
        history.append(epoch_stats)
        print(f"epoch {epoch} done in {epoch_stats['seconds']}s  "
              f"mean loss {epoch_stats['loss']:.4f}")

        torch.save(
            {
                "model": model.state_dict(),
                "epoch": epoch,
                "cfg": asdict(cfg),
                "criterion_config": asdict(criterion_config),
                "history": history,
            },
            ckpt_path,
        )
        print(f"  checkpoint -> {ckpt_path}")

        if stopped_early:
            break

    return model, history, ckpt_path


def predict_two_scale(model, coco, image_ids, cfg, index_to_cat_id,
                      views_for_consistency=False):
    """
    Run the detector at each scale in cfg.infer_scales and merge.

    Returns image_id -> {"boxes" (xyxy, ORIGINAL frame), "scores", "labels"},
    where labels are competition category_ids. With
    views_for_consistency=True it also returns the per-view detections, which is
    what Stage 3 needs to test whether a candidate survives a transformation.
    """
    import torch
    from PIL import Image

    device = next(model.parameters()).device
    model.eval()

    IMAGENET_MEAN = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
    IMAGENET_STD = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)

    by_id = {im["id"]: im for im in coco["images"]}
    out_final, out_views = {}, {}

    weights = list(cfg.infer_scale_weights)
    if len(weights) < len(cfg.infer_scales):
        weights += [1.0] * (len(cfg.infer_scales) - len(weights))

    def prep(pil, size):
        x = pil.resize((size, size), Image.BILINEAR)
        x = torch.from_numpy(np.asarray(x, dtype=np.float32).copy())
        x = x.permute(2, 0, 1) / 255.0
        return ((x - IMAGENET_MEAN) / IMAGENET_STD).unsqueeze(0)

    @torch.no_grad()
    def run(pil, size, W, H, flip=False):
        if flip:
            pil = pil.transpose(Image.FLIP_LEFT_RIGHT)
        pv = prep(pil, size).to(device)
        with autocast_ctx(bool(cfg.amp and device.type == "cuda")):
            o = model(pixel_values=pv)
        prob = o.logits[0].sigmoid().float().cpu().numpy()        # (Q, C)
        boxes = o.pred_boxes[0].float().cpu().numpy()             # (Q, 4) cxcywh norm

        # Flatten query x class into independent candidates, as DETR-family
        # post-processing does: one query may legitimately support two classes.
        q_idx, c_idx = np.where(prob >= cfg.score_threshold)
        if len(q_idx) == 0:
            return (np.zeros((0, 4)), np.zeros(0), np.zeros(0, dtype=int))

        scores = prob[q_idx, c_idx]
        b = boxes[q_idx]
        cx, cy, bw, bh = b[:, 0], b[:, 1], b[:, 2], b[:, 3]
        if flip:
            cx = 1.0 - cx
        xyxy = np.stack(
            [(cx - bw / 2) * W, (cy - bh / 2) * H,
             (cx + bw / 2) * W, (cy + bh / 2) * H], axis=1
        )
        return xyxy, scores, c_idx

    for n, im_id in enumerate(image_ids, 1):
        im = by_id[im_id]
        path = im.get("_local_path")
        if not path or not Path(path).is_file():
            continue
        try:
            pil = Image.open(path).convert("RGB")
        except Exception:
            continue
        W, H = pil.size

        passes, views = [], []
        for size, w in zip(cfg.infer_scales, weights):
            xyxy, scores, labels = run(pil, size, W, H)
            passes.append({"boxes": xyxy, "scores": scores, "labels": labels,
                           "size": (W, H), "weight": float(w)})
            views.append({"boxes": xyxy, "scores": scores, "labels": labels})

        if views_for_consistency:
            # One extra flipped view at the largest scale: a texture artifact
            # rarely reappears at the same place and class under a flip.
            xyxy, scores, labels = run(pil, max(cfg.infer_scales), W, H, flip=True)
            views.append({"boxes": xyxy, "scores": scores, "labels": labels})

        merged = merge_multiscale(
            passes,
            original_size=(W, H),
            method=cfg.softnms_method,
            sigma=cfg.softnms_sigma,
            iou_threshold=cfg.softnms_iou_threshold,
            score_threshold=cfg.score_threshold,
        )
        if len(merged["scores"]) > cfg.max_dets_per_image:
            keep = np.argsort(-merged["scores"])[: cfg.max_dets_per_image]
            merged = {k: merged[k][keep] for k in ("boxes", "scores", "labels")}

        # Map contiguous indices back to competition category_ids.
        merged["labels"] = np.array(
            [index_to_cat_id[int(i)] for i in merged["labels"]], dtype=np.int64
        )
        out_final[im_id] = merged
        if views_for_consistency:
            out_views[im_id] = views

        if n % 100 == 0:
            print(f"  inferred {n}/{len(image_ids)}")

    return (out_final, out_views) if views_for_consistency else out_final


def harvest_over_dataset(model, coco, image_ids, cfg, index_to_cat_id):
    """Run the Stage 3 funnel across a set of images and aggregate the counts."""
    cat_index_of = {v: k for k, v in index_to_cat_id.items()}

    _, views_by_image = predict_two_scale(
        model, coco, image_ids, cfg, index_to_cat_id, views_for_consistency=True
    )

    gt_by_image = collections.defaultdict(list)
    for a in coco["annotations"]:
        x, y, w, h = a["bbox"]
        gt_by_image[a["image_id"]].append(
            ([x, y, x + w, y + h], cat_index_of.get(a["category_id"], -1))
        )

    harvest, totals = {}, collections.Counter()
    for im_id, views in views_by_image.items():
        gt = gt_by_image.get(im_id, [])
        gt_boxes = np.array([g[0] for g in gt], dtype=float).reshape(-1, 4)
        gt_labels = np.array([g[1] for g in gt], dtype=int)

        res = harvest_pseudo_labels(
            views,
            gt_boxes=gt_boxes,
            gt_labels=gt_labels,
            score_threshold=cfg.pseudo_score_threshold,
            gt_iou_threshold=cfg.pseudo_gt_iou_threshold,
            consistency_iou=cfg.pseudo_consistency_iou,
            min_views=cfg.pseudo_min_views,
            max_per_image=cfg.pseudo_max_per_image,
        )
        for k, v in res["counts"].items():
            totals[k] += v
        if len(res["boxes"]):
            # Back to competition category_ids for merging into the COCO file.
            res["labels"] = np.array(
                [index_to_cat_id[int(i)] for i in res["labels"]], dtype=np.int64
            )
            harvest[im_id] = res

    print("\nStage 3 funnel across", len(views_by_image), "images:")
    for k in ("candidates", "after_confidence", "after_gt_dedup",
              "after_consistency", "kept"):
        print(f"  {k:20s} {totals[k]}")
    if totals["after_gt_dedup"]:
        survival = totals["after_consistency"] / totals["after_gt_dedup"]
        print(f"\n  consistency survival rate: {survival:.1%}")
        if survival > 0.9:
            print("  >>> consistency check is barely filtering - raise consistency_iou")
        elif survival < 0.05:
            print("  >>> almost nothing survives - lower the thresholds or this stage is a no-op")
    return harvest, dict(totals)


def evaluate_map(coco_gt_dict, predictions, index_to_name=None, verbose=True):
    """COCO mAP via pycocotools, plus the PU diagnostics worth reading beside it."""
    from pycocotools.coco import COCO
    from pycocotools.cocoeval import COCOeval
    import tempfile

    gt = {
        "images": coco_gt_dict["images"],
        "annotations": [
            dict(a, iscrowd=a.get("iscrowd", 0), area=a.get("area", a["bbox"][2] * a["bbox"][3]))
            for a in coco_gt_dict["annotations"]
        ],
        "categories": coco_gt_dict["categories"],
    }
    for i, a in enumerate(gt["annotations"], 1):
        a.setdefault("id", i)

    dets = []
    for im_id, p in predictions.items():
        for bb, sc, lab in zip(xyxy_to_xywh(p["boxes"]), p["scores"], p["labels"]):
            dets.append({
                "image_id": int(im_id), "category_id": int(lab),
                "bbox": [float(v) for v in bb], "score": float(sc),
            })

    if not dets:
        print("no detections - nothing to evaluate")
        return {"mAP": 0.0, "mAP50": 0.0, "n_dets": 0}

    with tempfile.TemporaryDirectory() as td:
        gt_path = Path(td) / "gt.json"
        dt_path = Path(td) / "dt.json"
        gt_path.write_text(json.dumps(gt))
        dt_path.write_text(json.dumps(dets))

        coco_gt = COCO(str(gt_path))
        coco_dt = coco_gt.loadRes(str(dt_path))
        e = COCOeval(coco_gt, coco_dt, "bbox")
        e.params.imgIds = sorted(predictions)
        e.evaluate(); e.accumulate()
        if verbose:
            e.summarize()
        else:
            import io, contextlib
            with contextlib.redirect_stdout(io.StringIO()):
                e.summarize()

    stats = {
        "mAP": float(e.stats[0]), "mAP50": float(e.stats[1]), "mAP75": float(e.stats[2]),
        "mAP_small": float(e.stats[3]), "mAP_medium": float(e.stats[4]),
        "mAP_large": float(e.stats[5]), "n_dets": len(dets),
    }

    # --- PU diagnostics ---------------------------------------------------
    per_class = collections.Counter(d["category_id"] for d in dets)
    scores = np.array([d["score"] for d in dets])
    stats["dets_per_image"] = len(dets) / max(len(predictions), 1)
    stats["n_high_conf"] = int((scores >= 0.5).sum())
    stats["mean_score"] = float(scores.mean())

    if verbose:
        print("\n--- PU diagnostics ---")
        print(f"detections/image      : {stats['dets_per_image']:.1f}")
        print(f"high-confidence (>=.5): {stats['n_high_conf']}")
        print(f"mean score            : {stats['mean_score']:.3f}")
        print(f"distinct classes used : {len(per_class)}")
        if index_to_name:
            name_of = {}
            for c in coco_gt_dict["categories"]:
                name_of[c["id"]] = c.get("name", str(c["id"]))
            print("top predicted classes :")
            for cid, n in per_class.most_common(8):
                print(f"   {name_of.get(cid, cid):26s} {n}")
        print(
            "\nReminder: on an incompletely annotated split a rise in "
            "'false positives'\nmay be recovered unlabeled organisms. Compare "
            "against the fully\nannotated evaluation set before concluding "
            "precision got worse."
        )
    return stats


def run_full_pipeline(coco_clean, test_json_path, train_ids, val_ids, cfg,
                      index_to_cat_id, index_to_name, prepare_images):
    """
    Execute every stage in one session under a wall-clock budget.

    `prepare_images(ids, coco, cfg)` resolves imagery and returns the ids that
    are actually on disk. Returns a dict summarising what each phase produced.
    """
    import csv
    import torch

    t0 = time.time()
    budget = float(cfg.time_budget_hours) * 3600.0
    reserve = min(float(cfg.reserve_hours) * 3600.0, budget * 0.5)
    train_budget = max(budget - reserve, 60.0)
    work = Path(cfg.work_dir)
    summary = {"phases": {}, "submission": None}

    def left():
        return budget - (time.time() - t0)

    def mark(msg):
        print(f"\n{'=' * 66}\n[{(time.time() - t0) / 3600:5.2f}h elapsed | "
              f"{left() / 3600:5.2f}h left]  {msg}\n{'=' * 66}")

    # Training time is split across the two fits and the harvest between them.
    # The harvest is inference-only, so it gets the smallest share.
    d_base = t0 + train_budget * 0.40
    d_harvest = t0 + train_budget * 0.60
    d_pu = t0 + train_budget

    # ---- phase 1: imagery ------------------------------------------------
    mark("PHASE 1/5  resolving training imagery")
    # Cap the fetch at a quarter of the training budget: imagery that has not
    # arrived by then costs more than it is worth.
    d_download = time.time() + train_budget * 0.25
    use_train = prepare_images(train_ids, coco_clean, cfg, deadline=d_download)
    use_val = prepare_images(val_ids, coco_clean, cfg, deadline=d_download)
    summary["phases"]["images"] = {"train": len(use_train), "val": len(use_val)}
    print(f"train {len(use_train)} | val {len(use_val)}")
    if not use_train:
        raise SystemExit("no training imagery could be resolved")

    # ---- phase 2: baseline ------------------------------------------------
    mark("PHASE 2/5  baseline detector (PU loss OFF)")
    cc_base = PULossConfig(
        num_classes=cfg.num_classes, pu_disabled=True,
        pseudo_label_weight=cfg.pseudo_label_weight,
    )
    model, hist, base_ckpt = train_one_run(
        coco_clean, use_train, use_val, cfg, cc_base, "rtdetr_base.pt",
        deadline=d_base,
    )
    summary["phases"]["train_base"] = {
        "epochs": len(hist), "final_loss": hist[-1]["loss"] if hist else None,
    }

    # ---- phase 3: pseudo-label harvest ------------------------------------
    coco_for_pu, added = coco_clean, 0
    if left() > reserve:
        mark("PHASE 3/5  conservative pseudo-label recovery")
        try:
            budget_ids = use_train
            harvest, totals = harvest_over_dataset(
                model, coco_clean, budget_ids, cfg, index_to_cat_id)
            coco_for_pu, added = merge_pseudo_labels(coco_clean, harvest)
            before = audit_coco(coco_clean)["instances_per_image"]["mean"]
            after = audit_coco(coco_for_pu)["instances_per_image"]["mean"]
            print(f"\nadded {added} pseudo-labels; "
                  f"instances/image {before:.2f} -> {after:.2f}")
            (work / "coco_with_pseudo.json").write_text(json.dumps(coco_for_pu))
            summary["phases"]["harvest"] = {"added": added, "funnel": totals,
                                            "instances_before": before,
                                            "instances_after": after}
        except Exception as e:
            print(f">>> harvest failed ({type(e).__name__}: {e}); "
                  "continuing with the cleaned data")
            summary["phases"]["harvest"] = {"error": f"{type(e).__name__}: {e}"}
    else:
        print(">>> skipping harvest: not enough time left")
        summary["phases"]["harvest"] = {"skipped": "out of time"}

    # ---- phase 4: PU retrain ----------------------------------------------
    final_ckpt = base_ckpt
    if left() > reserve:
        mark("PHASE 4/5  retrain with pseudo-labels + PU-aware background loss")
        try:
            cc_pu = PULossConfig(
                num_classes=cfg.num_classes,
                pu_w_min=cfg.pu_w_min, pu_w_max=cfg.pu_w_max,
                pu_tau=cfg.pu_tau, pu_temperature=cfg.pu_temperature,
                pu_disabled=cfg.pu_disabled,
                pseudo_label_weight=cfg.pseudo_label_weight,
            )
            print(f"PU: w_min={cc_pu.pu_w_min} w_max={cc_pu.pu_w_max} "
                  f"tau={cc_pu.pu_tau} T={cc_pu.pu_temperature}")
            model, hist_pu, pu_ckpt = train_one_run(
                coco_for_pu, use_train, use_val, cfg, cc_pu, "rtdetr_pu.pt",
                init_from=base_ckpt, deadline=d_pu,
            )
            final_ckpt = pu_ckpt
            summary["phases"]["train_pu"] = {
                "epochs": len(hist_pu),
                "final_loss": hist_pu[-1]["loss"] if hist_pu else None,
                "pseudo_labels_used": added,
            }
        except Exception as e:
            print(f">>> PU retrain failed ({type(e).__name__}: {e}); "
                  "falling back to the baseline checkpoint")
            summary["phases"]["train_pu"] = {"error": f"{type(e).__name__}: {e}"}
    else:
        print(">>> skipping PU retrain: not enough time left")
        summary["phases"]["train_pu"] = {"skipped": "out of time"}

    print(f"\nusing checkpoint: {final_ckpt}")

    # ---- phase 5: inference + submission (always) -------------------------
    mark("PHASE 5/5  two-scale inference + submission")
    if test_json_path is None:
        print(">>> no test annotations; cannot build a submission")
        return summary

    raw_test = load_coco(test_json_path)
    test_ids = [im["id"] for im in raw_test["images"]]
    if cfg.test_max_images:
        test_ids = test_ids[: cfg.test_max_images]
    print(f"test images declared: {len(test_ids)}")

    # The submission needs these, so give the test fetch most of the reserve.
    test_ids = prepare_images(test_ids, raw_test, cfg,
                              deadline=time.time() + reserve * 0.5)
    print(f"test images resolved: {len(test_ids)}")

    preds = predict_two_scale(model, raw_test, test_ids, cfg, index_to_cat_id)
    rows = build_submission(preds)

    sub = work / "submission.csv"
    with open(sub, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=SUBMISSION_COLUMNS)
        w.writeheader()
        w.writerows(rows)

    n_declared = len(raw_test["images"])
    covered = len(preds)
    print(f"\nsubmission: {len(rows)} rows -> {sub}")
    print(f"  images with >=1 detection: {covered}/{n_declared}")
    if covered < n_declared:
        print(f"  >>> {n_declared - covered} test images have no predictions "
              "(undownloadable or no detection above threshold); they score as "
              "missed")

    summary["submission"] = {
        "rows": len(rows), "images_covered": covered,
        "images_declared": n_declared, "path": str(sub),
        "checkpoint": str(final_ckpt),
    }

    # Validation diagnostics, only if there is time left over.
    if left() > 300 and use_val:
        try:
            mark("optional  validation diagnostics")
            vp = predict_two_scale(model, coco_clean, use_val, cfg, index_to_cat_id)
            summary["val_stats"] = evaluate_map(
                subset_coco(coco_clean, use_val), vp, index_to_name=index_to_name)
        except Exception as e:
            print(f"(validation diagnostics skipped: {type(e).__name__}: {e})")

    (work / "run_summary.json").write_text(json.dumps(summary, indent=2, default=str))
    mark(f"DONE in {(time.time() - t0) / 3600:.2f}h")
    return summary
